#!/bin/bash

ERRORS=0

#######################################################################
# basic tests made from artificial data, created in JOSM but never stored in the OSM DB (ids < 0)

TEST=$(basename $0 .script)

analyze-routes.pl --max-error=10 --check-access --check-name --check-stop-position --check-sequence --check-version --check-wide-characters \
                  --multiple-ref-type-entries=analyze --positive-notes --coloured-sketchline --verbose --debug \
                  --osm-xml-file=$TEST.osm > $TEST.html 2> $TEST.log

if [ -e $TEST.expect -a -s $TEST.html ]
then
    diff $TEST.expect $TEST.html > $TEST.diff
    
    if [ -s $TEST.diff ]
    then
        echo -e "failed with diff\t$TEST"
        ERRORS=$(( $ERRORS + 1 ))
    else
        echo -e "passed\t\t\t$TEST"
    fi
else
    echo -e "failed\t\t\t$TEST"
    ERRORS=$(( $ERRORS + 1 ))
fi

#######################################################################

exit $ERRORS

